apiVersion: v1
appVersion: 5.7.6
deprecated: true
description: DEPRECATED A Helm chart for Elasticsearch Curator
home: https://github.com/elastic/curator
keywords:
- curator
- elasticsearch
- elasticsearch-curator
name: elasticsearch-curator
sources:
- https://github.com/kubernetes/charts/elasticsearch-curator
- https://github.com/pires/docker-elasticsearch-curator
version: 2.2.3
